-- =============================================================
-- Poricito Bazar — PostgreSQL Database Schema
-- =============================================================
-- Run this file against your database to set up all tables:
--   psql -U <your_user> -d <your_db> -f database/schema.sql
-- =============================================================


-- ─────────────────────────────────────────────────────────────
-- 0. EXTENSIONS
-- ─────────────────────────────────────────────────────────────
-- pgcrypto gives us gen_random_uuid() for UUID primary keys.
CREATE EXTENSION IF NOT EXISTS "pgcrypto";


-- ─────────────────────────────────────────────────────────────
-- 1. PRODUCTS TABLE
-- ─────────────────────────────────────────────────────────────
-- Stores the product catalogue that the storefront renders.
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS products (
    id          SERIAL          PRIMARY KEY,

    -- Bengali product name shown on the frontend
    name        VARCHAR(200)    NOT NULL,

    -- Optional English / transliterated name for search / SEO
    name_en     VARCHAR(200),

    -- Price in BDT (Bangladeshi Taka). Stored as NUMERIC to avoid
    -- floating-point rounding issues.
    price       NUMERIC(10, 2)  NOT NULL CHECK (price >= 0),

    -- Unit label displayed next to the price, e.g. "লিটার", "কেজি"
    unit        VARCHAR(50)     NOT NULL DEFAULT 'পিস',

    -- Relative path to the product image served from /public
    image       TEXT            NOT NULL DEFAULT './assets/images/products/placeholder.jpg',

    -- Alt text for accessibility / SEO (Bengali)
    alt_text    TEXT,

    -- Category used for filter tabs on the frontend
    -- e.g. 'তেল', 'মশলা', 'চিনি', 'মধু', 'চাল'
    category    VARCHAR(100),

    -- Optional badge label rendered on the card, e.g. 'নতুন', 'বেস্টসেলার'
    badge       VARCHAR(50),

    -- Controls whether the "অর্ডার করুন" button is active
    in_stock    BOOLEAN         NOT NULL DEFAULT TRUE,

    -- Audit timestamps (auto-managed)
    created_at  TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

-- Index for common filter queries (?category=তেল)
CREATE INDEX IF NOT EXISTS idx_products_category ON products (category);
CREATE INDEX IF NOT EXISTS idx_products_in_stock  ON products (in_stock);


-- ─────────────────────────────────────────────────────────────
-- 2. ORDERS TABLE
-- ─────────────────────────────────────────────────────────────
-- Each row represents one product line in a customer's order.
-- A cart with 3 products will INSERT 3 rows sharing an order_ref.
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS orders (
    id              SERIAL          PRIMARY KEY,

    -- Human-readable order reference, e.g. "PB-1712345678901"
    -- Generated by the application before insert.
    order_ref       VARCHAR(30)     NOT NULL,

    -- FK to the products table. SET NULL on product deletion so
    -- historical orders are never lost.
    product_id      INTEGER         REFERENCES products (id) ON DELETE SET NULL,

    -- Snapshot of the product name at order time (in case product
    -- is later renamed or deleted).
    product_name    VARCHAR(200)    NOT NULL,

    -- How many units the customer ordered
    quantity        INTEGER         NOT NULL CHECK (quantity > 0),

    -- Unit price snapshot at the time of ordering
    unit_price      NUMERIC(10, 2)  NOT NULL CHECK (unit_price >= 0),

    -- Computed total: quantity × unit_price (stored for reporting)
    total_price     NUMERIC(12, 2)  GENERATED ALWAYS AS (quantity * unit_price) STORED,

    -- Customer details
    customer_name   VARCHAR(200)    NOT NULL,
    phone           VARCHAR(20)     NOT NULL,
    address         TEXT            NOT NULL,

    -- Order lifecycle status
    -- pending → confirmed → shipped → delivered | cancelled
    status          VARCHAR(20)     NOT NULL DEFAULT 'pending'
                        CHECK (status IN ('pending','confirmed','shipped','delivered','cancelled')),

    -- Optional note from the admin
    admin_note      TEXT,

    -- Audit timestamps
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

-- Indexes for admin dashboard queries
CREATE INDEX IF NOT EXISTS idx_orders_order_ref   ON orders (order_ref);
CREATE INDEX IF NOT EXISTS idx_orders_status      ON orders (status);
CREATE INDEX IF NOT EXISTS idx_orders_created_at  ON orders (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_orders_phone       ON orders (phone);


-- ─────────────────────────────────────────────────────────────
-- 3. AUTO-UPDATE updated_at TRIGGER
-- ─────────────────────────────────────────────────────────────
-- Keeps updated_at in sync automatically on every UPDATE.

CREATE OR REPLACE FUNCTION trigger_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Attach to products
DROP TRIGGER IF EXISTS set_updated_at_products ON products;
CREATE TRIGGER set_updated_at_products
    BEFORE UPDATE ON products
    FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();

-- Attach to orders
DROP TRIGGER IF EXISTS set_updated_at_orders ON orders;
CREATE TRIGGER set_updated_at_orders
    BEFORE UPDATE ON orders
    FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();


-- ─────────────────────────────────────────────────────────────
-- 4. SEED DATA — initial product catalogue
-- ─────────────────────────────────────────────────────────────
-- INSERT … ON CONFLICT DO NOTHING makes this script safely re-runnable.

INSERT INTO products (name, name_en, price, unit, image, alt_text, category, badge, in_stock)
VALUES
    ('খাঁটি সরিষার তেল',       'Pure Mustard Oil',        400.00, 'লিটার',    './assets/images/products/mustard-oil.jpg',       'খাঁটি সরিষার তেল - Pure Mustard Oil',        'তেল',   'বেস্টসেলার', TRUE),
    ('বিশুদ্ধ নারিকেল তেল',    'Pure Coconut Oil',         440.00, '৮০০ml',    './assets/images/products/coconut-oil.jpg',       'বিশুদ্ধ নারিকেল তেল - Pure Coconut Oil',     'তেল',    NULL,         TRUE),
    ('প্রাকৃতিক হলুদের গুঁড়া','Natural Turmeric Powder',  200.00, '২০০গ্রাম', './assets/images/products/turmeric-powder.jpg',   'প্রাকৃতিক হলুদের গুঁড়া',                    'মশলা',  'নতুন',       TRUE),
    ('দেশী সাল চিনি',           'Deshi Cane Sugar',         120.00, 'কেজি',     './assets/images/products/cane-sugar.jpg',        'দেশী সাল চিনি - Deshi Cane Sugar',           'চিনি',   NULL,         TRUE),
    ('আখের গুড়',               'Raw Cane Jaggery',         180.00, 'কেজি',     './assets/images/products/jaggery.jpg',           'আখের গুড় - Raw Cane Jaggery',                'চিনি',   NULL,         TRUE),
    ('খাঁটি মধু',               'Pure Honey',               650.00, '৫০০ml',    './assets/images/products/honey.jpg',             'খাঁটি মধু - Pure Honey',                     'মধু',   'প্রিমিয়াম', TRUE),
    ('লাল চাল',                  'Red Rice',                  90.00, 'কেজি',     './assets/images/products/red-rice.jpg',          'লাল চাল - Red Rice',                         'চাল',    NULL,         FALSE),
    ('ঘানি ভাঙা সরিষার তেল',   'Cold-Pressed Mustard Oil', 520.00, 'লিটার',    './assets/images/products/cold-pressed-oil.jpg',  'ঘানি ভাঙা সরিষার তেল - Cold-Pressed Oil',    'তেল',   'অর্গানিক',  TRUE)
ON CONFLICT DO NOTHING;


-- =============================================================
-- 5. USERS TABLE (customer accounts)
-- =============================================================
CREATE TABLE IF NOT EXISTS users (
    id              SERIAL          PRIMARY KEY,

    -- Full name (Bengali or English)
    full_name       VARCHAR(200)    NOT NULL,

    -- Unique email — used as login identifier
    email           VARCHAR(255)    NOT NULL UNIQUE,

    -- bcrypt-hashed password (never store plain text)
    password_hash   TEXT            NOT NULL,

    -- Optional profile fields
    phone           VARCHAR(20),
    address         TEXT,
    district        VARCHAR(100),
    thana           VARCHAR(100),

    -- Account status
    is_active       BOOLEAN         NOT NULL DEFAULT TRUE,
    is_verified     BOOLEAN         NOT NULL DEFAULT FALSE,

    -- Audit timestamps
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    last_login_at   TIMESTAMPTZ
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_users_email     ON users (email);
CREATE INDEX IF NOT EXISTS idx_users_phone     ON users (phone);
CREATE INDEX IF NOT EXISTS idx_users_is_active ON users (is_active);

-- Auto-update trigger
DROP TRIGGER IF EXISTS set_updated_at_users ON users;
CREATE TRIGGER set_updated_at_users
    BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();

-- =============================================================
-- 6. Link orders → users (optional FK, SET NULL on delete)
-- =============================================================
-- Add user_id to orders if it doesn't exist yet
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name='orders' AND column_name='user_id'
  ) THEN
    ALTER TABLE orders ADD COLUMN user_id INTEGER REFERENCES users(id) ON DELETE SET NULL;
    CREATE INDEX idx_orders_user_id ON orders(user_id);
  END IF;
END $$;
